library(tidyverse)
library(randomForest)
library(caret)
library(rpart)
library(modelr)
train <- read.csv("../input/train.csv")
str(train)
test <- read.csv("../input/test.csv")
train <- (train[complete.cases(train), ])
train$Adult <- ifelse(train$Age < 18, 0, 1)
train %>% group_by(Sex) %>% summarize(mean(Survived))
train %>% group_by(Pclass) %>% summarize(mean(Survived))
ggplot(data = train, aes(x = Adult, y = Survived, color = Sex)) + geom_point() + geom_jitter()
fit <- rpart(Survived ~ Sex + Pclass + Age + Adult + Fare, data = train)
plot(fit)
text(fit)
test$Adult <- ifelse(test$Age < 18, 0, 1)
ps <- predict(fit, test)
ps <- ifelse(ps > 0.5, 1, 0)
pid <- test$PassengerId
final <- data.frame(PassengerId = pid, Survived = ps)
write.csv(final, file = "PredictedSurvivors.csv", row.names = FALSE)
