library(rpart)
train <- read.csv("../input/train.csv")
test <- read.csv("../input/test.csv")
fit <- rpart(Survived ~ Pclass + Sex + Age + Fare, data = train, method = "class")
prediction <- predict(fit, test, type = "class")
result <- data.frame(PassengerId = test$PassengerId, Survived = prediction)
write.csv(result, "result.csv", row.names = FALSE)
