train <- read.csv("../input/train.csv")
test <- read.csv("../input/test.csv")
logistic <- glm(Survived ~ SibSp + Parch + Sex + Pclass, data = train, family = "binomial")
summary(logistic)
predicted <- predict(logistic, test, type = "response")
predicted <- round(predicted)
output <- data.frame(test$PassengerId, predicted)
colnames(output) <- cbind("PassengerId", "Survived")
write.csv(output, file = "Rushton_Solution.csv", row.names = F)
