library(ggplot2)
library(readr)
library(rpart)
library(rpart.plot)
system("ls ../input")
dat = read.csv("../input/train.csv")
colSums(is.na(dat))
summary(dat)
str(dat)
dat$familySize = dat$SibSp + dat$Parch
ggplot(dat, aes(x = familySize, fill = Survived == 1)) + geom_bar(position = "fill") + ggtitle("Survival rate by Family Size(discrete)") + ylab("Prob of survival")
dat$familySize = ifelse(dat$familySize > 6, "large", ifelse(dat$familySize > 3, "medium", ifelse(dat$familySize > 0, "small", "single")))
ggplot(dat, aes(x = familySize, fill = Survived == 1)) + geom_bar(position = "fill") + ggtitle("Survival rate by Family Size(categorical)") + ylab("Prob of survival")
nam = dat$Name
head(nam)
title = gsub("(.*,)|(\\..*)", "", nam)
head(title)
unique(title)
table(title)
dat = data.frame(dat, title)
dat$title = gsub("Mme", "Mrs", dat$title)
dat$title = gsub("Mlle", "Miss", dat$title)
dat$title = gsub("Ms", "Miss", dat$title)
dat$title = gsub("Lady", "hon", dat$title)
dat$title = gsub("Sir", "hon", dat$title)
dat$title = gsub("Don", "hon", dat$title)
dat$title = gsub("Jonkheer", "hon", dat$title)
dat$title = gsub("the Countess", "hon", dat$title)
dat$title = gsub("Capt", "hon", dat$title)
dat$title = gsub("Col", "hon", dat$title)
dat$title = gsub("Major", "hon", dat$title)
dat$title = gsub("Dr", "hon", dat$title)
ggplot(dat, aes(x = title, fill = Survived == 1)) + geom_bar(position = "fill") + ggtitle("Survival rate by Title") + ylab("Prob of survival")
index = which(is.na(dat$Embarked))
index
dat$Embarked[index] = "S"
dat$Survived = as.factor(dat$Survived)
dat$Pclass = as.factor(dat$Pclass)
modd = rpart(Survived ~ ., data = dat[, -c(1, 4, 7, 8, 9, 11)], method = "class")
printcp(modd)
modd1 = prune(modd, cp = 0.01)
prp(modd1)
modd1
test = read.csv("../input/test.csv")
str(test)
test$Pclass = as.factor(test$Pclass)
test$familySize = test$SibSp + test$Parch
test$familySize = ifelse(test$familySize > 6, "large", ifelse(test$familySize > 3, "medium", ifelse(test$familySize > 0, "small", "single")))
colSums(is.na(test))
ind = which(is.na(test$Fare))
test$Pclass[ind]
aggregate(Fare ~ Pclass, test, mean)
test$Fare[ind] = 12.4597
nam1 = test$Name
head(nam1)
title = gsub("(.*,)|(\\..*)", "", nam1)
head(title)
unique(title)
table(title)
test = data.frame(test, title)
unique(test$title)
test$title = gsub("Mme", "Mrs", test$title)
test$title = gsub("Mlle", "Miss", test$title)
test$title = gsub("Ms", "Miss", test$title)
test$title = gsub("Lady", "hon", test$title)
test$title = gsub("Sir", "hon", test$title)
test$title = gsub("Dona", "hon", test$title)
test$title = gsub("Jonkheer", "hon", test$title)
test$title = gsub("the Countess", "hon", test$title)
test$title = gsub("Capt", "hon", test$title)
test$title = gsub("Col", "hon", test$title)
test$title = gsub("Major", "hon", test$title)
test$title = gsub("Dr", "hon", test$title)
Survived = predict(modd1, type = "class", newdata = test)
Survived
PassengerId = test$PassengerId
result = data.frame(PassengerId, Survived)
write.csv(result, "Submission_Fin.csv", row.names = F)
