library(e1071)
train <- read.csv("../input/train.csv")
test <- read.csv("../input/test.csv")
BayesTitanicModel <- naiveBayes(as.factor(Survived) ~ ., train)
str(BayesTitanicModel)
BayesPrediction <- predict(BayesTitanicModel, test)
str(BayesPrediction)
summary(BayesPrediction)
output <- data.frame(test$PassengerId, BayesPrediction)
str(output)
colnames(output) <- cbind("PassengerId", "Survived")
write.csv(output, file = "Rushton_Solution.csv", row.names = F)
