---
title: "Titanic"
author: "g4ravity"
date: "2018年8月22日"
output: 
  html_document:
    number_section: yes
    toc: yes
---

# 导入相关R包

```{r warning = FALSE,message = FALSE}
library(caret)
library(dplyr)
library(VIM)
library(mice)
library(randomForest)
```

# 读取数据

```{r}
train <- read.csv(file = "../input/train.csv")
test <- read.csv(file = "../input/test.csv")
sub <- read.csv(file = "../input/gender_submission.csv")
```

# 数据处理

## 查看数据结构

```{r}
str(train)
str(test)
train$Survived <- as.factor(train$Survived)
levels(test$Embarked) <- levels(train$Embarked)
```

## 数据缺失值处理

### 训练集

```{r,fig.width = 9}
aggr(train,numbers = TRUE)
colSums(is.na(train))
train$Age[is.na(train$Age)] <- mean(train$Age,na.rm = T)
```

### 测试集

```{r fig.width = 9}
aggr(test,numbers = TRUE)
colSums(is.na(test))
test$Age[is.na(test$Age)] <- mean(test$Age,na.rm = T)
test$Fare[is.na(test$Fare)] <- mean(test$Fare,na.rm = T)
```

# 随机森林

## 数据准备

```{r}
trainInd <- createDataPartition(train$Survived,p = 0.8,list = FALSE)
train_X <- train[trainInd,]
train_Y <- train[-trainInd,]
```

## 训练模型

```{r}
set.seed(5)
RF <- randomForest(Survived ~ .,data = train_X[,-c(1,4,9,11)],ntree = 2000)
pred <- predict(RF,newdata = train_Y)
pred
pred_result <- bind_cols(train_Y,"pred" = pred)
pred_result[,c(1,2,13)]
```

## 查看模型准确率

```{r}
cm <- table(train_Y$Survived,pred)
accuracy <- sum(diag(cm))/sum(cm)
accuracy
```

## 测试模型

```{r}
set.seed(6)
Pred <- predict(RF,newdata = test)
Pred
```

## 输出结果

```{r}
submission <- cbind(sub,"Survived" = Pred)
submission <- submission[,c(1,3)]
write.csv(submission,file = "submission.csv",row.names=FALSE)
```