library("ggplot2")
library("ggthemes")
library("scales")
library("dplyr")
library("mice")
library("randomForest")
train <- read.csv("../input/train.csv", stringsAsFactors = F)
test <- read.csv("../input/test.csv", stringsAsFactors = F)
str(train)
str(test)
full <- bind_rows(train, test)
str(full)
unique(full$Survived)
sum(is.na(full$PassengerId))
sum(is.na(full$Survived))
sum(is.na(full$Pclass))
sum(is.na(full$Name))
sum(is.na(full$Sex))
sum(is.na(full$Age))
sum(is.na(full$SibSp))
sum(is.na(full$Parch))
sum(is.na(full$Ticket))
sum(is.na(full$Fare))
sum(full$Cabin == "")
sum(full$Embarked == "")
full$Title <- gsub("(.*, )|(\\..*)", "", full$Name)
table(full$Sex, full$Title)
rare_title <- c("Dona", "Lady", "the Countess", "Capt", "Col", "Don", "Dr", "Major", "Rev", "Sir", "Jonkheer")
full$Title[full$Title == "Mlle"] <- "Miss"
full$Title[full$Title == "Ms"] <- "Miss"
full$Title[full$Title == "Mme"] <- "Mrs"
full$Title[full$Title %in% rare_title] <- "Rare Title"
table(full$Sex, full$Title)
full$Surname <- sapply(full$Name, function(x) strsplit(x, split = "[,.]")[[1]][1])
full$FamSize <- full$SibSp + full$Parch + 1
full$Family <- paste(full$Surname, full$FamSize, sep = "_")
ggplot(full[1:891, ], aes(x = FamSize, fill = factor(Survived))) + geom_bar(stat = "count", position = "dodge") + scale_x_continuous(breaks = c(1:11)) + labs(x = "Family Size") + theme_few()
numSurvived = sum(train$Survived)
numDied = nrow(train) - numSurvived
PropSurvived = numSurvived/nrow(train)
PropDied = numDied/nrow(train)
byClass <- group_by(train, Survived, Pclass)
summarise(byClass, train = n())
ggplot(full[1:891, ], aes(x = Pclass, fill = factor(Survived))) + geom_bar(stat = "count", position = "dodge") + scale_x_continuous(breaks = c(1:11)) + labs(x = "Class") + theme_few()
table(train$Survived, train$Sex)
table(train$Embarked, train$Survived)
full$Missing_Age = ifelse(is.na(full$Age), 1, 0)
full$Missing_Cabin = ifelse(full$Cabin == "", 1, 0)
full$NumCharName = nchar(full$Name)
full$NumCharTicket <- nchar(full$Ticket)
full$FirstCharTicket <- factor(sapply(full$Ticket, function(x) strsplit(x, NULL)[[1]][1]))
full$FirstCharCabin <- factor(sapply(full$Cabin, function(x) strsplit(x, NULL)[[1]][1]))
which(full$Embarked == "")
cat(paste("We will infer their values for **embarkment** based on present data that we can imagine may be relevant: \n**passenger class** and **fare**. We see that they paid<b> $", full[c(62, 830), "Fare"][[1]][1], "</b>and<b> $", full[c(62, 830), "Fare"][[1]][2], "</b>respectively and their classes are<b>", full[c(62, 830), "Pclass"][[1]][1], "</b>and<b>", full[c(62, 830), "Pclass"][[1]][2], "</b>. So from where did they embark?"))
embark_fare <- full %>% filter(PassengerId != 62 & PassengerId != 830)
ggplot(embark_fare, aes(x = Embarked, y = Fare, fill = factor(Pclass))) + geom_boxplot() + geom_hline(aes(yintercept = 80), colour = "red", linetype = "dashed", lwd = 2) + scale_y_continuous(labels = dollar_format()) + theme_few()
full$Embarked[c(62, 830)] <- "C"
which(full$Fare == "")
full[1044, ]
ggplot(full[full$Pclass == "3" & full$Embarked == "S", ], aes(x = Fare)) + geom_density(fill = "#99d6ff", alpha = 0.4) + geom_vline(aes(xintercept = median(Fare, na.rm = T)), colour = "red", linetype = "dashed", lwd = 1) + scale_x_continuous(labels = dollar_format()) + theme_few()
full$Fare[1044] <- median(full[full$Pclass == "3" & full$Embarked == "S", ]$Fare, na.rm = TRUE)
factor_vars <- c("PassengerId", "Pclass", "Sex", "Embarked", "Title", "Surname", "Family", "FirstCharCabin", "FirstCharTicket")
full[factor_vars] <- lapply(full[factor_vars], function(x) as.factor(x))
set.seed(129)
mice_mod <- mice(full[, !names(full) %in% c("PassengerId", "Name", "Ticket", "Cabin", "Family", "Surname", "Survived", "FirstCharCabin", "FirstCharTicket")], method = "rf")
mice_output <- complete(mice_mod)
par(mfrow = c(1, 2))
hist(full$Age, freq = F, main = "Age: Original Data", col = "darkgreen", ylim = c(0, 0.04))
hist(mice_output$Age, freq = F, main = "Age: MICE Output", col = "lightgreen", ylim = c(0, 0.04))
full$Age <- mice_output$Age
sum(is.na(full$Age))
train <- full[1:891, ]
test <- full[892:1309, ]
set.seed(1234)
rf_model <- randomForest(factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + Title + FamSize + FirstCharTicket + Missing_Age + Missing_Cabin + NumCharName + NumCharTicket, data = train)
plot(rf_model, ylim = c(0, 0.36))
legend("topright", colnames(rf_model$err.rate), col = 1:3, fill = 1:3)
importance <- importance(rf_model)
varImportance <- data.frame(Variables = row.names(importance), Importance = round(importance[, "MeanDecreaseGini"], 2))
rankImportance <- varImportance %>% mutate(Rank = paste0("#", dense_rank(desc(Importance))))
ggplot(rankImportance, aes(x = reorder(Variables, Importance), y = Importance, fill = Importance)) + geom_bar(stat = "identity") + geom_text(aes(x = Variables, y = 0.5, label = Rank), hjust = 0, vjust = 0.55, size = 4, colour = "red") + labs(x = "Variables") + coord_flip() + theme_few()
set.seed(1234)
rf_model2 <- randomForest(factor(Survived) ~ Title + Sex + Fare + NumCharName + Age + FirstCharTicket + Pclass + FamSize + NumCharTicket + Missing_Cabin, data = train)
plot(rf_model2, ylim = c(0, 0.36))
legend("topright", colnames(rf_model$err.rate), col = 1:3, fill = 1:3)
set.seed(1234)
rf_model3 <- randomForest(factor(Survived) ~ Title + Sex + Fare + NumCharName + Age, data = train)
plot(rf_model3, ylim = c(0, 0.36))
legend("topright", colnames(rf_model$err.rate), col = 1:3, fill = 1:3)
prediction <- predict(rf_model, test)
solution <- data.frame(PassengerID = test$PassengerId, Survived = prediction)
write.csv(solution, file = "rf_mod_Solution.csv", row.names = F)
