library(caret)
library(randomForest)
trainSet <- read.table("../input/train.csv", sep = ",", header = TRUE)
testSet <- read.table("../input/test.csv", sep = ",", header = TRUE)
trainSet$Survived <- factor(trainSet$Survived)
set.seed(42)
trainSet$Survived <- factor(trainSet$Survived)
set.seed(42)
model <- train(Survived ~ Pclass + Sex + SibSp + Embarked + Parch + Fare, data = trainSet, method = "rf", trControl = trainControl(method = "cv", number = 5))
testSet$Fare <- ifelse(is.na(testSet$Fare), mean(testSet$Fare, na.rm = TRUE), testSet$Fare)
testSet$Survived <- predict(model, newdata = testSet)
submission <- testSet[c("PassengerId", "Survived")]
write.table(submission, file = "submission.csv", col.names = TRUE, row.names = FALSE, sep = ",")
