train_data <- read.csv("../input/train.csv")
test_data <- read.csv("../input/test.csv")
str(train_data)
head(train_data)
tail(train_data)
summary(train_data$Age)
train_data$Age[is.na(train_data$Age)] <- mean(train_data$Age, na.rm = TRUE)
test_data$Age[is.na(test_data$Age)] <- mean(test_data$Age, na.rm = TRUE)
test_data$Fare[is.na(test_data$Fare)] <- mean(test_data$Fare, na.rm = TRUE)
class(train_data$Survived)
levels(as.factor(train_data$Survived))
head(train_data$Survived)
train_data$Survived <- ifelse(train_data$Survived == 1, "yes", "no")
train_data$Survived <- as.factor(train_data$Survived)
head(train_data$Survived)
class(train_data$Survived)
library(rpart)
table(as.factor(train_data$Survived))
train_data$Survived <- as.factor(train_data$Survived)
str(train_data$Survived)
tree <- rpart(formula = Survived ~ Sex + Age + SibSp + Parch + Fare + Embarked, data = train_data, method = "class")
library(rattle)
library(rpart.plot)
library(RColorBrewer)
fancyRpartPlot(tree)
test_data$Survived <- 0
Prediction <- predict(tree, test_data, type = "class")
prop.table(table(Prediction))
test_data$Survived <- Prediction
survived <- ifelse(test_data$Survived == "no", 0, 1)
submit <- data.frame(PassengerId = test_data$PassengerId, Survived = survived)
write.csv(submit, file = "arpit_titanic.csv", row.names = FALSE)
library(caret)
confusionMatrix(Prediction, test_data$Survived)
