library(randomForest)
titanic.train <- read.csv("../input/train.csv")
titanic.test <- read.csv("../input/test.csv")
summary(titanic.train)
titanic.test$Survived <- rep(0, 418)
submit <- data.frame(PassengerId = titanic.test$PassengerId, Survived = titanic.test$Survived)
write.csv(submit, file = "EmptyResult.csv", row.names = FALSE)
randomForest(as.factor(Survived) ~ Pclass + Sex + SibSp, data = titanic.train, ntree = 5000, importance = TRUE)
