library(tidyverse) # metapackage with lots of helpful functions
library(rpart)
library(stringr)
library(doSNOW)
library(RColorBrewer)
library(dplyr)
library(ggplot2)
library(party)
library(rpart.plot)
library(xgboost)
library(drat)
library(beanplot)
library(RCurl, quietly = T)
library(tidyverse, quietly = T)
library(ggplot2)
library(gridExtra, quietly = T)
library(beanplot, quietly = T)
library(caret, quietly = T)
library(stringr, quietly = T)
library(party, quietly = T)
library(xgboost, quietly = T)
library(skimr, quietly = T)
library(alluvial, quietly = T)
library(pROC, quietly = T)
library(ggrepel, quietly = T)
library(Amelia)
