library(dplyr)
library(randomForest)
library(rpart)
library(ggplot2)
train <- read.csv("../input/train.csv")
test <- read.csv("../input/test.csv")
set.seed(111)
train$Pclass <- as.numeric(as.character(train$Pclass))
test$Pclass <- as.numeric(as.character(test$Pclass))
all_data <- bind_rows(train, test)
all_data <- as.data.frame(all_data, na.rm = TRUE)
str(all_data)
names(all_data)
ggplot(all_data, aes(x = factor("Survived"), fill = Sex)) + geom_bar()
is.na(all_data)
is.na(all_data$Fare[1044])
all_data$Fare[1044] <- median(all_data$Fare, na.rm = TRUE)
is.na(all_data$Embarked)
is.na(all_data$Embarked[c(62, 830)])
all_data$Pclass <- as.factor(all_data$Pclass)
all_data$Embarked[c(62, 830)] <- "S"
all_data$Embarked <- factor(all_data$Embarked)
prediction_age <- rpart(Age ~ Pclass + Sex + SibSp + Parch + Fare + Embarked, data = all_data[!is.na(all_data$Age), ], method = "anova")
all_data$Age[is.na(all_data$Age)] <- predict(prediction_age, all_data[is.na(all_data$Age), ])
is.na(all_data$Age[c(1:750)])
is.na(all_data$Age[c(751:1309)])
is.na(all_data[1:300, ])
is.na(all_data[, 1:3])
all_data$Title <- gsub("(.*, )|(\\..*)", "", all_data$Name)
table(all_data$Title)
str(all_data)
ggplot(all_data, aes(Title, fill = Title)) + geom_bar()
table(all_data$Sex, all_data$Title)
table(all_data$Sex, all_data$Pclass)
table(all_data$Pclass, all_data$Title)
all_data$Title[all_data$Title == "Mlle"] <- "Miss"
all_data$Title[all_data$Title == "Ms"] <- "Miss"
all_data$Title[all_data$Title == "Mme"] <- "Mrs"
all_data$Title[all_data$Title == "Dona"] <- "Mrs"
all_data$Title[all_data$Title == "Don"] <- "Mr"
question_status <- c("Dr", "Lady", "the Countess", "Capt", "Col", "Major", "Rev", "Sir", "Jonkheer")
all_data$Title[all_data$Title %in% question_status] <- "question status"
table(all_data$Title, all_data$Sex)
ggplot(all_data, aes(Title, fill = Title)) + geom_bar()
all_data$Married_Woman <- "Not Married"
all_data$Married_Woman[all_data$Sex == "female" & all_data$Title != "Mrs"] <- "Married_Woman"
str(all_data)
table(all_data$Sex, all_data$Married_Woman)
all_data$Survived <- as.factor(all_data$Survived)
all_data$Title <- as.factor(all_data$Title)
all_data$Married_Woman <- as.factor(all_data$Married_Woman)
str(all_data)
train_again <- all_data[1:891, ]
test_again <- all_data[892:1309, ]
set.seed(112)
my_forest <- randomForest(as.factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + Title + Married_Woman, data = train_again, importance = TRUE, ntree = 1000)
my_prediction <- predict(my_forest, newdata = test_again)
importance <- importance(my_forest)
varImportance <- data.frame(Variables = row.names(importance), Importance = round(importance[, "MeanDecreaseGini"], 2))
varImpPlot(my_forest)
rankImportance <- varImportance %>% mutate(Rank = paste0("#", dense_rank(desc(Importance))))
ggplot(rankImportance, aes(x = reorder(Variables, Importance), y = Importance, fill = Importance)) + geom_bar(stat = "identity") + geom_text(aes(x = Variables, y = 0.5, label = Rank), hjust = 0, vjust = 0.55, size = 4, colour = "red") + labs(x = "Variables") + coord_flip() + theme_classic()
my_solution <- data.frame(PassengerId = test_again$PassengerId, Survived = my_prediction)
write.csv(my_solution, file = "my_RF_solution.csv", row.names = FALSE)
