library(randomForest)
library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
print(date())
print("Prabhat's code")
train <- read.csv("../input/train.csv")
test <- read.csv("../input/test.csv")
str(train)
str(test)
summary(train)
summary(test)
table(train$Survived)
table(train$Sex, train$Survived)
png("1_survival_by_class.png", width = 800, height = 600)
mosaicplot(train$Pclass ~ train$Survived, main = "Passenger Survival by Class", color = c("#8dd3c7", "#fb8072"), shade = FALSE, xlab = "", ylab = "", off = c(0), cex.axis = 1.4)
dev.off()
my_tree_two <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, data = train, method = "class")
plot(my_tree_two)
text(my_tree_two)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
fancyRpartPlot(my_tree_two)
my_prediction <- predict(my_tree_two, newdata = test, type = "class")
my_solution <- data.frame(PassengerId = test$PassengerId, Survived = my_prediction)
nrow(my_solution)
write.csv(my_solution, file = "my_solution.csv", row.names = FALSE)
