titanic.train <- read.csv("../input/train.csv", stringsAsFactors = FALSE)
titanic.test <- read.csv("../input/test.csv", stringsAsFactors = FALSE)
str(titanic.train)
str(titanic.train)
summary(titanic.train)
summary(titanic.train)
sum(is.na(titanic.train))
sum(is.na(titanic.train$Age))
table(titanic.train$Embarked)
sum(is.na(titanic.train$Fare))
sum(is.na(titanic.test))
sum(is.na(titanic.test$Age))
table(titanic.test$Embarked)
sum(is.na(titanic.test$Fare))
ncol(titanic.train)
ncol(titanic.test)
titanic.train$isTrainSet <- TRUE
titanic.test$isTrainSet <- FALSE
colnames(titanic.train)
colnames(titanic.test)
titanic.test$Survived <- NA
dim(titanic.train)
dim(titanic.test)
Titanic.full <- rbind(titanic.train, titanic.test)
418 + 891
sum(is.na(Titanic.full))
table(Titanic.full$Embarked)
Titanic.full[Titanic.full$Embarked == "", "Embarked"] <- "S"
table(is.na(Titanic.full$Age))
sum(is.na(Titanic.full$Age))
titanic.age_median <- median(Titanic.full$Age, na.rm = TRUE)
Titanic.full[is.na(Titanic.full$Age), "Age"] <- titanic.age_median
table(is.na(Titanic.full$Fare))
sum(is.na(Titanic.full$Fare))
titanic.fare_median <- median(Titanic.full$Fare, na.rm = TRUE)
Titanic.full[is.na(Titanic.full$Fare), "Fare"] <- titanic.fare_median
Titanic.full$Pclass <- as.factor(Titanic.full$Pclass)
Titanic.full$Sex <- as.factor(Titanic.full$Sex)
Titanic.full$Embarked <- as.factor(Titanic.full$Embarked)
str(Titanic.full)
titanic.train <- Titanic.full[Titanic.full$isTrainSet == TRUE, ]
titanic.test <- Titanic.full[Titanic.full$isTrainSet == FALSE, ]
sum(is.na(titanic.train$Age))
sum(is.na(titanic.train$Fare))
sum(is.na(titanic.train$Embarked))
sum(is.na(titanic.test$Age))
sum(is.na(titanic.test$Fare))
sum(is.na(titanic.test$Embarked))
sum(is.na(titanic.train))
sum(is.na(titanic.test))
titanic.train$isTrainSet <- NULL
titanic.test$isTrainSet <- NULL
titanic.test$Survived <- NULL
titanic.train$Survived <- as.factor(titanic.train$Survived)
colnames(titanic.train)
library(randomForest)
rf <- randomForest(formula = Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, data = titanic.train, ntree = 300)
print(rf)
attributes(rf)
library(caret)
library(lubridate)
library(lattice)
library(ggplot2)
prd.train <- predict(rf, titanic.train)
print(head(prd.train))
prd.test <- predict(rf, titanic.test)
print(head(prd.test))
print(tail(prd.test))
plot(rf)
PassengerId <- titanic.test$PassengerId
str(PassengerId)
PassengerId.df <- as.data.frame(PassengerId)
str(PassengerId.df)
PassengerId.df$Survived <- prd.test
tail(PassengerId.df)
write.csv(PassengerId.df, file = "Titanic_Kaggle_Submission.csv", row.names = FALSE)
hist(treesize(rf), main = "no of nodes per tress", col = "green")
varImpPlot(rf)
varImpPlot(rf, sort = TRUE, n.var = 5)
