library(ggplot2)
library(readr)
system("ls ../input")
train = read.csv("../input/train.csv")
train = train[, -c(1, 4, 9, 11)]
set.seed(1)
train$Age[is.na(train$Age)] = sample(train$Age[!is.na(train$Age)], 177)
set.seed(2)
train$Embarked[train$Embarked == ""] = sample(train$Embarked[train$Embarked != ""], 2)
train$Embarked = as.character(train$Embarked)
train$Embarked = as.factor(train$Embarked)
train$Survived = as.factor(train$Survived)
summary(train)
library(randomForest)
set.seed(3)
rf.fit = randomForest(Survived ~ ., data = train)
rf.pred = predict(rf.fit, newdata = train)
table(true = train$Survived, pred = rf.pred)
mean(train$Survived == rf.pred)
test_original = read.csv("../input/test.csv")
test = test_original
test = test[, -c(1, 3, 8, 10)]
test = data.frame(Survived = as.factor(rep(0, 418)), test)
set.seed(1)
test$Age[is.na(test$Age)] = sample(test$Age[!is.na(test$Age)], 86)
set.seed(2)
test$Fare[is.na(test$Fare)] = sample(test$Fare[!is.na(test$Fare)], 1)
names(test)
levels(test$Survived) = levels(train$Survived)
levels(test$Embarked) = levels(train$Embarked)
test$Survived = predict(rf.fit, test)
prediction = data.frame(PassengerId = test_original$PassengerId, Survived = test$Survived)
summary(prediction)
head(prediction)
write.csv(prediction, "gender_submission.csv")
