library(readr)
library(dplyr)
library(ggplot2)
library(missForest)
library(rpart)
library(rpart.plot)
library(randomForest)
train <- read_csv("../input/train.csv")
test <- read_csv("../input/test.csv")
all <- bind_rows(train, test)
str(all)
summary(all)
head(all)
tail(all)
sapply(all, function(x) sum(is.na(x)))
table(train$Survived)
ggplot(all[1:891, ], aes(x = Pclass, fill = factor(Survived))) + geom_bar(stat = "count", position = "stack") + ggtitle("Survival Based on Ticket Class") + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_discrete(name = "Survived") + scale_x_continuous(breaks = c(1:11))
all[1:891, ] %>% group_by(Pclass) %>% summarise(survived_percentage = (sum(Survived)/length(Pclass) * 100))
table(train$Pclass, train$Sex)
table(train[train$Survived == 1, ]$Pclass, train[train$Survived == 1, ]$Sex)
all$Pclass <- as.factor(all$Pclass)
name_split <- strsplit(all$Name, split = "[,.]")
name_title <- sapply(name_split, "[", 2)
name_title <- substring(name_title, 2)
table(name_title)
uncommon_titles <- c("Capt", "Col", "Don", "Dona", "Dr", "Jonkheer", "Lady", "Major", "Rev", "Sir", "the Countess")
name_title[name_title %in% uncommon_titles] <- "uncommon"
name_title[name_title == "Mlle"] <- "Miss"
name_title[name_title %in% c("Mme", "Ms")] <- "Mrs"
all <- mutate(all, Title = name_title)
all$Title <- as.factor(all$Title)
rm(name_split, name_title, uncommon_titles)
ggplot(all[1:891, ], aes(x = Sex, fill = factor(Survived))) + geom_bar(stat = "count", position = "stack") + ggtitle("Survival Based on Gender") + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_discrete(name = "Survived")
all$Sex <- as.factor(all$Sex)
sum(is.na(all$Age))
age.mis <- as.data.frame(all[, c(2, 3, 5, 6, 7, 8, 10, 12)])
age.mis$Embarked <- as.factor(age.mis$Embarked)
age.mis$Survived <- as.factor(age.mis$Survived)
age_imp <- missForest(age.mis)
age_new <- age_imp[[1]][4]
age_new <- as.numeric(age_new$Age)
hist(age_new, freq = F)
median(age_new)
all$Age <- age_new
ggplot(all[1:891, ], aes(factor(Survived), Age)) + geom_boxplot() + ggtitle("Survival Based on Age") + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_discrete(name = "Survived")
rm(age_imp, age_new, age.mis)
all <- mutate(all, family_size = SibSp + Parch + 1)
ggplot(all[1:891, ], aes(x = family_size, fill = factor(Survived))) + geom_bar(stat = "count", position = "dodge") + ggtitle("Survival Based on family size") + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_discrete(name = "Survived") + scale_x_continuous(breaks = c(1:11))
all$family_size <- ifelse(all$family_size == 1, "single", ifelse(all$family_size > 4, "big", "medium"))
all$family_size <- as.factor(all$family_size)
ticket_count <- rep("NA", times = nrow(all))
for (i in 1:nrow(all)) {
    ticket_count[i] <- nrow(all[all$Ticket == all$Ticket[i], ])
}
all <- mutate(all, ticket_count)
ggplot(all[1:891, ], aes(x = as.numeric(ticket_count), fill = factor(Survived))) + geom_bar(stat = "count", position = "dodge") + ggtitle("Survival Based on Ticket Count") + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_discrete(name = "Survived") + scale_x_continuous(breaks = c(1:11))
all$ticket_count <- ifelse(all$ticket_count == 1, "single", ifelse(all$ticket_count > 4, "big", "medium"))
all$ticket_count <- as.factor(all$ticket_count)
family_size <- all$SibSp + all$Parch + 1
cor(family_size, as.numeric(ticket_count), method = "pearson")
rm(family_size, i, ticket_count)
all[is.na(all$Fare), ]
all[is.na(all$Fare), ]$Fare <- median(all[(all$Embarked == "S" & all$Sex == "male" & all$Pclass == "3"), "Fare"]$Fare, na.rm = T)
all[1044, "Fare"]
ggplot(all, aes(x = Fare)) + geom_density(kernel = "gaussian") + ggtitle("Density Plot for Fare Variable") + theme(plot.title = element_text(hjust = 0.5))
all <- mutate(all, Fare_ln = as.numeric(ifelse(all$Fare == 0, "NA", log(all$Fare))))
ggplot(all, aes(x = Fare_ln)) + geom_density(kernel = "gaussian") + ggtitle("Density Plot for Fare_ln Variable") + theme(plot.title = element_text(hjust = 0.5))
all[is.na(all$Embarked), ]
all %>% filter(Pclass == 1 & Sex == "female" & ticket_count == "medium") %>% group_by(Embarked) %>% summarise(avg_fare = median(Fare))
all[is.na(all$Embarked), ]$Embarked <- "S"
all[c(62, 830), "Embarked"]
all$Embarked <- as.factor(all$Embarked)
mother <- rep("NA", times = nrow(all))
for (i in 1:nrow(all)) {
    mother[i] <- ifelse(all$Sex[i] == "female" & all$Age[i] > 16 & all$Parch[i] > 0 & nrow(all[all$Ticket == all$Ticket[i], ]) > 1, ifelse(any((all[all$Ticket == all$Ticket[i] & all$Age < 10 & all$Parch > 0, ]$Age + 16) < all$Age[i]), 1, 0), 0)
}
all <- all %>% mutate(mother)
all$mother <- as.factor(all$mother)
rm(mother, i)
all <- mutate(all, child = ifelse(all$Age < 10, 1, 0))
all$child <- as.factor(all$child)
train_model <- all[1:891, c("Survived", "Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Fare_ln", "Embarked", "Title", "family_size", "ticket_count", "mother", "child")]
test_model <- all[892:1309, c("Survived", "Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Fare_ln", "Embarked", "Title", "family_size", "ticket_count", "mother", "child")]
reg0 <- glm(Survived ~ 1, data = train_model, family = binomial)
reg1 <- glm(Survived ~ ., data = train_model, family = binomial)
step(reg0, scope = formula(reg1), direction = "forward", k = 2)
logistic_forward <- glm(Survived ~ Title + Pclass + family_size + Age + Sex, data = train_model, family = binomial)
decision_tree <- rpart(Survived ~ ., data = train_model, method = "class")
rpart.plot(decision_tree)
random_forest <- randomForest(as.factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + Title + family_size + ticket_count + mother + child, data = train_model, importance = TRUE, ntree = 2000)
varImpPlot(random_forest)
pred_log <- predict(logistic_forward, newdata = test_model, type = "response")
classification <- ifelse(pred_log > 0.5, 1, 0)
Prediction_logistic <- data.frame(PassengerId = test$PassengerId, Survived = classification)
write.csv(Prediction_logistic, file = "logistic.csv", row.names = FALSE)
pred_tree <- predict(decision_tree, newdata = test_model, type = "class")
Prediction_tree <- data.frame(PassengerId = test$PassengerId, Survived = pred_tree)
write.csv(Prediction_tree, file = "tree.csv", row.names = FALSE)
pred_random <- predict(random_forest, newdata = test_model)
Prediction_random <- data.frame(PassengerId = test$PassengerId, Survived = pred_random)
write.csv(Prediction_random, file = "random.csv", row.names = FALSE)
