library(ggplot2)
library(readr)
system("ls ../input")
library(caret)
library(reshape2)
test <- read.csv("../input/test.csv", header = TRUE)
train <- read.csv("../input/train.csv", header = TRUE)
train.missingData.vector <- apply(train[, -2], 2, function(x) sum(is.na(x) | x == ""))
train.missingData.column <- melt(train.missingData.vector)
train$Age[is.na(train$Age)] <- mean(train$Age, na.rm = TRUE)
train$Embarked[which(is.na(train$Embarked) | train$Embarked == "")] <- "S"
fol <- formula(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked)
library(rpart)
decisionTreeModel <- rpart(fol, method = "class", data = train)
prediction <- predict(decisionTreeModel, test, type = "class")
test$Survived <- as.numeric(as.numeric(prediction) == 1)
write.csv(test[, c("PassengerId", "Survived")], "submission.csv", row.names = F)
