train <- read.csv("../input/train.csv", header = T, na.strings = c(""))
test <- read.csv("../input/test.csv", header = T, na.strings = c(""))
str(train)
library(ggplot2)
table(train$Survived)
prop.table(table(train$Survived))
ggplot(train, aes(Survived, fill = "salmon")) + geom_bar()
train$Pclass <- as.factor(train$Pclass)
table(train$Pclass)
ggplot(train, aes(Pclass, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
library(stringr)
Title <- as.factor(str_sub(train$Name, str_locate(train$Name, ",")[, 1] + 2, str_locate(train$Name, "\\.")[, 1] - 1))
table(train$Sex, Title)
ggplot(train, aes(Title, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
NameLength <- nchar(as.character(train$Name))
NameLenCat <- cut(NameLength, seq(12, 82, 5))
table(train$Survived, NameLenCat)
ggplot(train, aes(NameLenCat, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
ggplot(train, aes(Sex, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
summary(train$Age)
ggplot(train, aes(Age)) + geom_density(kernel = "gaussian")
table(train$Survived, is.na(train$Age))
Age_Null <- is.na(train$Age)
Agecat <- cut(train$Age, seq(0, 85, 8))
ggplot(train, aes(Agecat, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
table(train$SibSp)
ggplot(train, aes(SibSp, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
table(train$Parch)
ggplot(train, aes(Parch, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
TicketType <- substring(train$Ticket, 1, 1)
TicketType2 <- nchar(as.character(train$Ticket))
TicketType <- as.factor(TicketType)
TicketType2 <- as.factor(TicketType2)
ggplot(train, aes(TicketType, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
ggplot(train, aes(TicketType2, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
length(unique(train$Fare))
aggregate(Fare ~ Pclass, train, mean)
library(DT)
sum(!is.na(train$Cabin))
length(unique(train$Cabin))
sum(is.na(train$Cabin))
datatable(data.frame(summary(train$Cabin)))
CabinType <- substring(train$Cabin, 1, 1)
ggplot(train, aes(CabinType, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
table(train$Embarked)
datatable(train[is.na(train$Embarked), ])
ggplot(train, aes(Embarked, ..count.., fill = factor(Survived))) + geom_bar(position = "dodge")
ggplot(train, aes(Embarked, ..count.., fill = factor(Pclass))) + geom_bar(position = "dodge")
Survived <- train$Survived
train$Survived <- NULL
combi <- rbind(train, test)
combi$Title <- as.factor(str_sub(combi$Name, str_locate(combi$Name, ",")[, 1] + 2, str_locate(combi$Name, "\\.")[, 1] - 1))
c_NameLength <- nchar(as.character(combi$Name))
combi$NameLenCat <- cut(c_NameLength, seq(11, 86, 5))
combi$FamilySize <- combi$SibSp + combi$Parch + 1
combi$TicketLett <- as.factor(substring(combi$Ticket, 1, 1))
combi$TicketLen <- as.factor(nchar(as.character(combi$Ticket)))
combi$CabinType <- substring(combi$Cabin, 1, 1)
combi$CabinType[is.na(combi$CabinType)] <- "N"
combi$CabinType <- as.factor(combi$CabinType)
combi$Embarked[is.na(combi$Embarked)] <- "S"
combi$Fare[is.na(combi$Fare)] <- mean(combi[combi$Pclass == 3 & combi$Embarked == "S" & combi$TicketLen == 4 & combi$CabinType == "N", "Fare"], na.rm = TRUE)
library(rpart)
Agefit <- rpart(Age ~ Pclass + Sex + SibSp + Parch + Fare + Embarked + Title + NameLenCat + FamilySize + TicketLett + TicketLen + CabinType, data = combi[!is.na(combi$Age), ], method = "anova")
combi$Age[is.na(combi$Age)] <- predict(Agefit, combi[is.na(combi$Age), ])
train <- cbind(Survived, combi[1:nrow(train), c(2, 4, 5, 6, 7, 9, 11, 12, 13, 14, 15, 16, 17)])
test <- combi[(nrow(train) + 1):nrow(combi), c(2, 4, 5, 6, 7, 9, 11, 12, 13, 14, 15, 16, 17)]
library(randomForest)
set.seed(777)
fit <- randomForest(as.factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + Title + NameLenCat + FamilySize + TicketLett + TicketLen + CabinType, data = train, importance = TRUE, ntree = 2000)
varImpPlot(fit)
Prediction <- predict(fit, test)
submit <- data.frame(PassengerId = c(892:1309), Survived = Prediction)
write.csv(submit, file = "randomforest.csv", row.names = FALSE)
