install.packages(c("ggplot2", "ISLR", "MASS", "glmnet", "randomForest", "gbm", "rpart", "boot"))
install.packages("dplyr")
library(ggplot2)
library(ISLR)
library(MASS)
library(glmnet)
library(randomForest)
library(gbm)
library(rpart)
library(boot)
library(dplyr)
select <- dplyr::select
titanic_train <- read.csv("../input/train.csv", stringsAsFactors = F, na.strings = c("NA", ""))
titanic_test <- read.csv("../input/test.csv", stringsAsFactors = F, na.strings = c("NA", ""))
`?`(read.csv)
glimpse(titanic_train)
str(titanic_train)
glimpse(titanic_test)
titanic_test$Survived <- NA
titanic_all <- rbind(titanic_train, titanic_test)
titanic_all$Sex <- as.factor(titanic_all$Sex)
titanic_all$Survived <- as.factor(titanic_all$Survived)
titanic_all$Pclass <- as.ordered(titanic_all$Pclass)
sapply(titanic_all, function(x) {
    sum(is.na(x))
})
sapply(titanic_train, function(x) {
    sum(is.na(x))
})
ggplot(titanic_train[!is.na(titanic_train$Survived), ], aes(x = Survived, fill = Survived)) + geom_bar(stat = "count") + labs(x = "타이타닉 생존") + geom_label(stat = "count", aes(label = ..count..), size = 7)
ggplot(titanic_train, aes(x = Sex, fill = Sex)) + geom_bar(stat = "count", position = "dodge")
labs(x = "train_성별") + geom_label(stat = "count", aes(label = ..count..))
ggplot(titanic_train, aes(x = Pclass, fill = Pclass)) + geom_bar(stat = "count", position = "dodge") + labs(x = "Pclass, train_좌석등급") + geom_label(stat = "count", aes(label = ..count..)) + theme(legend.position = "none")
install.packages("sqldf")
library(sqldf)
sqldf("select *, (Survived/Total)\n       from( select A.Survived, B.Total, A.sex \n             from(select count(*) Survived, Sex\n                  from titanic_train\n                  where Survived = 1\n                  group by Sex ) A\n             inner join (select count(*) Total, Sex\n                    from titanic_train\n                    group by Sex) B\n        on A.Sex = B.Sex \n       ) T\n      ")
sqldf("select *, (Survived/Total)\n       from(select A.Survived, B.Total, A.Pclass \n            from(select count(*) Survived, Pclass\n                 from titanic_train\n                 where Survived = 1 \n                 group by Pclass) A\n                  inner join (select count(*) Total, Pclass\n                              from titanic_train\n                              group by Pclass) B\n        on A.Pclass = B.Pclass \n      ) T\n      ")
sqldf("select *\n       from (select A.Survived, B.Total, A.Pclass, A.Sex \n            from (select count(*) Survived, Pclass, Sex\n                  from titanic_train\n                  where Survived = 1 \n                  group by Sex, Pclass) A\n                    inner join (select count(*) Total, Pclass, Sex\n                                from titanic_train\n                                group by Sex, Pclass) B\n                  on A.Pclass = B.Pclass \n                  and A.Sex = B.Sex\n            ) T\n     ")
sqldf("select A.sibsp, Survived, Total\n       from (select sibsp, count(*) Survived \n             from titanic_train \n             where Survived = 1\n             group by sibsp) A \n       inner join ( select sibsp, count(*) Total \n                     from titanic_train \n                     group by sibsp\n                    ) B\n        on A.sibsp = B.sibsp \n      ")
sqldf("select A.Parch, Survived, Total\n       from (select Parch, count(*) Survived \n             from titanic_train \n             where Survived = 1\n             group by Parch) A \n       inner join ( select Parch, count(*) Total \n                    from titanic_train \n                    group by Parch\n                  ) B\n       on A.Parch = B.Parch \n      ")
sqldf("select A.Embarked, Survived, Total\n       from (select Embarked, count(*) Survived \n            from titanic_train \n            where Survived = 1\n            group by Embarked) A \n            inner join ( select Embarked, count(*) Total \n                          from titanic_train \n                          group by Embarked\n                          ) B\n      on A.Embarked = B.Embarked \n      ")
set.seed(1777)
n <- nrow(titanic_train)
idx <- 1:n
`?`(sample)
training_idx <- sample(idx, n * 0.8)
validate_idx <- setdiff(idx, training_idx)
length(training_idx)
length(validate_idx)
training <- titanic_train[training_idx, ]
validation <- titanic_train[validate_idx, ]
glm_first <- glm(Survived ~ Age + Pclass + Sex + SibSp + Parch + Fare, data = training, family = binomial)
summary(glm_first)
glm_predictions <- predict(glm_first, newdata = validation, type = "response")
validation$pred_survived <- as.numeric(glm_predictions > 0.5)
validation$pred_survived <- ifelse(is.na(validation$pred_survived), 0, validation$pred_survived)
print(validation$pred_survived)
got_right <- with(validation, pred_survived == Survived)
got_wrong <- with(validation, pred_survived != Survived)
n_right <- sum(got_right, na.rm = TRUE)
n_wrong <- sum(got_wrong, na.rm = TRUE)
accuracy <- n_right/(n_right + n_wrong)
cat("accuracy: ", accuracy, "\n")
titanic_test$Survived <- ifelse(predict(glm_first, titanic_test, type = "response") > 0.5, 1, 0)
titanic_test$Survived <- ifelse(is.na(titanic_test$Survived), 0, titanic_test$Survived)
submission <- titanic_test[, c("PassengerId", "Survived")]
glimpse(submission)
write.csv(submission, "submission.csv", row.names = FALSE)
print(list.files())
