library(ggplot2)
library(dplyr)
library(ggthemes)
Titanic_train <- read.csv("../input/train.csv")
Titanic_test <- read.csv("../input/test.csv")
glimpse(Titanic_train)
Titanic_train$Pclass <- as.factor(Titanic_train$Pclass)
levels(Titanic_train$Pclass) <- c("Upper", "Middle", "Lower")
glimpse(Titanic_train)
Titanic_train$Sex <- as.factor(Titanic_train$Sex)
levels(Titanic_train$Sex) <- c("Female", "Male")
glimpse(Titanic_train)
sum(Titanic_train$Survived == 1)
sum(Titanic_train$Survived == 0)
Sex_Distribution <- ggplot(data = Titanic_train, aes(x = Sex)) + geom_bar(fill = "green", width = 0.7) + ylab("num_of_passenger") + ggtitle("Sex and passenger numbers relationship")
Sex_Distribution
sum(Titanic_train$Survived == 1 & Titanic_train$Sex == "Female")
sum(Titanic_train$Survived == 1 & Titanic_train$Sex == "Male")
sum(Titanic_train$Survived == 0 & Titanic_train$Sex == "Female")
sum(Titanic_train$Survived == 0 & Titanic_train$Sex == "Male")
Titanic_train1 <- Titanic_train %>% select(Survived, Pclass, Sex, Age) %>% filter(Age >= 0)
Age_Distribution <- ggplot() + geom_density(data = Titanic_train1, aes(x = Age), fill = "yellow", alpha = 0.7)
Age_Distribution
max(Titanic_train$Age, na.rm = TRUE)
min(Titanic_train$Age, na.rm = TRUE)
sum(Titanic_train1$Age < 10 & Titanic_train1$Survived == 1)/sum(Titanic_train1$Age < 10)
sum(Titanic_train1$Age >= 10 & Titanic_train1$Age < 30 & Titanic_train1$Survived == 1)/sum(Titanic_train1$Age >= 10 & Titanic_train1$Age < 30)
sum(Titanic_train1$Age >= 30 & Titanic_train1$Age < 50 & Titanic_train1$Survived == 1)/sum(Titanic_train1$Age >= 30 & Titanic_train1$Age < 50)
sum(Titanic_train1$Age >= 50 & Titanic_train1$Survived == 1)/sum(Titanic_train1$Age >= 50)
Pclass_Distribution <- ggplot(data = Titanic_train, aes(x = Pclass)) + geom_bar(fill = "blue", width = 0.7) + ylab("num_of_passenger") + ggtitle("Relationship between Pclass and passenger numbers")
Pclass_Distribution
sum(Titanic_train$Pclass == "Upper" & Titanic_train$Survived == 1)/sum(Titanic_train$Pclass == "Upper")
sum(Titanic_train$Pclass == "Middle" & Titanic_train$Survived == 1)/sum(Titanic_train$Pclass == "Middle")
sum(Titanic_train$Pclass == "Lower" & Titanic_train$Survived == 1)/sum(Titanic_train$Pclass == "Lower")
Titanic_train$FamilySize <- ifelse(Titanic_train$SibSp + Titanic_train$Parch + 1 == 1, "Single", ifelse(Titanic_train$SibSp + Titanic_train$Parch + 1 < 4, "Small", "Large"))
FamilySize_Distribution <- ggplot(Titanic_train, aes(FamilySize)) + geom_bar(position = "dodge", fill = "orange") + scale_x_discrete(limits = c("Single", "Small", "Large")) + ylab("num_of_passenger") + ggtitle("Family size and passenger numbers")
FamilySize_Distribution
Familysize_Survived <- ggplot(Titanic_train, aes(FamilySize, fill = factor(Survived))) + geom_bar() + theme_few() + xlab("Familysize") + ylab("num_of_passengers") + scale_fill_discrete(name = "Survived") + theme_few() + ggtitle("Relationship between Familysize and Survived")
Familysize_Survived
sum(Titanic_train$FamilySize == "Single" & Titanic_train$Survived == 1)/sum(Titanic_train$FamilySize == "Single")
sum(Titanic_train$FamilySize == "Small" & Titanic_train$Survived == 1)/sum(Titanic_train$FamilySize == "Small")
sum(Titanic_train$FamilySize == "Large" & Titanic_train$Survived == 1)/sum(Titanic_train$FamilySize == "Large")
Titanic_train_model <- Titanic_train %>% filter(Age >= 0) %>% select(Sex, Age, Pclass, FamilySize, Survived)
Titanic_model <- lm(Survived ~ Sex + Age + Pclass + FamilySize, data = Titanic_train_model)
summary(Titanic_model)
Titanic_test$FamilySize <- ifelse(Titanic_test$SibSp + Titanic_test$Parch + 1 == 1, "Single", ifelse(Titanic_test$SibSp + Titanic_test$Parch + 1 < 4, "Small", "Large"))
Titanic_test$Pclass <- as.factor(Titanic_test$Pclass)
levels(Titanic_test$Pclass) <- c("Upper", "Middle", "Lower")
Titanic_test$Sex <- as.factor(Titanic_test$Sex)
levels(Titanic_test$Sex) <- c("Female", "Male")
submission <- Titanic_test %>% mutate(Survived = round(predict(Titanic_model, Titanic_test))) %>% select(PassengerId, Survived)
submission[is.na(submission)] <- 0
submission
write.csv(submission, file = "Titanic.csv", row.names = F)
