---
title: 'Mice and caret for titanic survival'
author: 'Scott G. Daniel'
date: '2018-10-31'
output:
  html_document:
    number_sections: true
    toc: true
    fig_width: 7
    fig_height: 4.5
    theme: readable
    highlight: tango
editor_options: 
  chunk_output_type: console
---

# Introduction

I'm an experienced R user ([my github](https://www.github.com/scottdaniel) for examples) but this is my first time doing machine learning in R. I'm going to use *mice* for fixing the missing data (imputing!) and *caret* for model-building and prediction. 

# Setup libraries and load files

## Libraries

```{r, message = FALSE}
library(mice) #this should also load lattice
library(caret) #this should also load ggplot2
library('dplyr') # data manipulation
```

## Data files

```{r, message=FALSE, warning=FALSE}
train <- read.csv('../input/train.csv', stringsAsFactors = F)
test  <- read.csv('../input/test.csv', stringsAsFactors = F)

full  <- bind_rows(train, test) # bind training & test data

# check data
str(full)
```


# Impute missing values

# Model training

# Prediction

# Output and Conclusion
