library(ggplot2)
library(readr)
list.files("../input")
library(rpart)
library(rpart.plot)
library(RColorBrewer)
train = read.csv("../input/train.csv")
test = read.csv("../input/test.csv")
str(train)
my_tree_two <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, data = train, method = "class")
plot(my_tree_two)
text(my_tree_two)
fancyRpartPlot(my_tree_two)
my_tree_two
my_prediction <- predict(my_tree_two, newdata = test, type = "class")
my_solution <- data.frame(PassengerId = test$PassengerId, Survived = my_prediction)
nrow(my_solution)
write.csv(my_solution, file = "my_solution.csv", row.names = FALSE)
my_tree_three <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, data = train, method = "class", control = rpart.control(minsplit = 50, cp = 0))
fancyRpartPlot(my_tree_three)
my_prediction3 <- predict(my_tree_three, newdata = test, type = "class")
my_solution3 <- data.frame(PassengerId = test$PassengerId, Survived = my_prediction3)
write.csv(my_solution3, file = "my_solution3.csv", row.names = FALSE)
