library(randomForest)
train <- read.csv("../input/train.csv")
test <- read.csv("../input/test.csv")
summary(train)
train$Survived <- factor(train$Survived, levels = c(1, 0))
levels(train$Survived) <- c("Survived", "Died")
train$Pclass <- as.factor(train$Pclass)
levels(train$Pclass) <- c("1st Class", "2nd Class", "3rd Class")
png("1_survival_by_class.png", width = 800, height = 600)
mosaicplot(train$Pclass ~ train$Survived, main = "Passenger Survival by Class", color = c("#8dd3c7", "#fb8072"), shade = FALSE, xlab = "", ylab = "", off = c(0), cex.axis = 1.4)
dev.off()
library(ggplot2)
library(randomForest)
set.seed(1)
train <- read.csv("../input/train.csv", stringsAsFactors = FALSE)
test <- read.csv("../input/test.csv", stringsAsFactors = FALSE)
extractFeatures <- function(data) {
    features <- c("Pclass", "Age", "Sex", "Parch", "SibSp", "Fare", "Embarked")
    fea <- data[, features]
    fea$Age[is.na(fea$Age)] <- -1
    fea$Fare[is.na(fea$Fare)] <- median(fea$Fare, na.rm = TRUE)
    fea$Embarked[fea$Embarked == ""] = "S"
    fea$Sex <- as.factor(fea$Sex)
    fea$Embarked <- as.factor(fea$Embarked)
    return(fea)
}
rf <- randomForest(extractFeatures(train), as.factor(train$Survived), ntree = 100, importance = TRUE)
submission <- data.frame(PassengerId = test$PassengerId)
submission$Survived <- predict(rf, extractFeatures(test))
write.csv(submission, file = "1_random_forest_r_submission.csv", row.names = FALSE)
imp <- importance(rf, type = 1)
featureImportance <- data.frame(Feature = row.names(imp), Importance = imp[, 1])
p <- ggplot(featureImportance, aes(x = reorder(Feature, Importance), y = Importance)) + geom_bar(stat = "identity", fill = "#53cfff") + coord_flip() + theme_light(base_size = 20) + xlab("") + ylab("Importance") + ggtitle("Random Forest Feature Importance\n") + theme(plot.title = element_text(size = 18))
ggsave("2_feature_importance.png", p)
