library(tidyverse)
library(dplyr)
train <- read.table("../input/train.csv", header = TRUE, sep = ",")
test <- read.table("../input/test.csv", header = TRUE, sep = ",")
str(train)
summary(train)
i <- 1
write_to_file <- function(pred_vec, type) {
    submit1 <- data.frame(test2$PassengerId, pred_vec)
    colnames(submit1)[1] <- "PassengerId"
    submit1$Survived <- submit1$pred_vec
    str(submit1)
    table(submit1$Survived)
    submit1$pred_vec <- NULL
    str(submit1)
    filename <- paste("submission_", type, i, ".csv", sep = "")
    write.csv(submit1, filename, row.names = FALSE)
    i <- i + 1
}
sum(is.na(train))
missing <- colSums(is.na(train))
sort(missing, decreasing = TRUE)
library(mice)
md.pattern(train)
library(VIM)
mice_plot <- aggr(train, col = c("navyblue", "yellow"), numbers = TRUE, sortVars = TRUE, labels = names(train), cex.axis = 0.7, gap = 3, ylab = c("Missing data", "Pattern"))
library(DMwR)
train2 <- centralImputation(train)
sum(is.na(train2))
str(train2)
train3 <- train2
train3$Survived <- as.factor(train3$Survived)
str(train3)
hist(train3$Age)
hist(train3$SibSp)
hist(train3$Parch)
hist(train3$Fare)
train4 <- train3[, c("Pclass", "Sex", "Age", "SibSp", "Survived", "Parch", "Fare", "Embarked")]
set.seed(123)
library(caTools)
spl <- sample.split(train4, 0.9)
train5 <- train4[spl == TRUE, ]
valid <- train4[spl == FALSE, ]
sum(is.na(test))
library(DMwR)
test2 <- centralImputation(test)
test3 <- test2[, c("Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked")]
library(rpart)
model_cart <- rpart(Survived ~ ., data = train5, method = "class", control = rpart.control(cp = 0.019, minbucket = 5))
summary(model_cart)
library(rpart.plot)
prp(model_cart, varlen = 10)
plotcp(model_cart)
library(caret)
pred_train <- predict(model_cart, train5, type = "class")
confusionMatrix(pred_train, train5$Survived)
pred_valid <- predict(model_cart, newdata = valid, type = "class")
confusionMatrix(pred_valid, valid$Survived)
pred_cart <- predict(model_cart, newdata = test3, type = "class")
write_to_file(pred_cart, "CART_new")
library(randomForest)
model_random <- randomForest(Survived ~ ., data = train5, importance = TRUE, ntree = 55)
summary(model_random)
plot(model_random)
importance(model_random)
library(caret)
pred_rf <- predict(model_random, train5, type = "class")
confusionMatrix(pred_rf, train5$Survived)
pred_valid_rf <- predict(model_random, valid)
confusionMatrix(pred_valid_rf, valid$Survived)
levels(test3$Embarked) <- levels(train5$Embarked)
pred_rft <- predict(model_random, test3)
write_to_file(pred_rft, "RandomF")
