library(dplyr)
library(ggplot2)
library(ggthemes)
library(randomForest)
library(mice)
train <- read.csv("../input/train.csv")
test <- read.csv("../input/test.csv")
full <- bind_rows(train, test)
str(train)
str(test)
str(full)
summary(full)
full$Survived <- as.factor((full$Survived))
full$Pclass <- as.factor(full$Pclass)
full$Embarked <- as.factor(full$Embarked)
full$title <- gsub("(.*, )|(\\..*)", "", full$Name)
table(full$title, full$Survived)
table(full$Sex, full$title)
rare_title <- c("Dona", "Lady", "the Countess", "Capt", "Col", "Don", "Dr", "Major", "Rev", "Sir", "Jonkheer")
full$title[full$title == "Mlle"] <- "Miss"
full$title[full$title == "Ms"] <- "Miss"
full$title[full$title == "Mme"] <- "Mrs"
full$title[full$title %in% rare_title] <- "Others"
full$title <- as.factor(full$title)
full$Family <- full$Parch + full$SibSp + 1
prop.table(table(full$Family, full$Survived), 1)
ggplot(full[1:891, ], aes(x = Family, fill = Survived)) + geom_bar(stat = "count", position = "dodge") + scale_x_continuous(breaks = c(1:11)) + theme_few()
full$FType <- "NA"
full$FType <- ifelse(full$Family == 1, "single", ifelse(full$Family > 1 & full$Family <= 4, "small", "Large"))
full$FType <- as.factor(full$FType)
prop.table(table(full$FType, full$Survived), 1)
ggplot(full[1:891, ], aes(x = FType, fill = Survived)) + geom_bar(stat = "count", position = "dodge")
table(full$Sex, full$Survived)
prop.table(table(full$Sex, full$Survived), 1)
ggplot(full[1:891, ], aes(x = Sex, fill = Survived)) + geom_bar(stat = "count", position = "dodge")
prop.table(table(full$Fare, full$Survived), 1)
ggplot(full[1:891, ], aes(x = Fare, fill = Survived)) + geom_density()
prop.table(table(full$Pclass, full$Survived), 1)
ggplot(full[1:891, ], aes(x = Pclass, fill = Survived)) + geom_bar(stat = "count", position = "dodge")
full$Embarked <- as.factor(full$Embarked)
prop.table(table(full$Embarked))
ggplot(full, aes(x = Embarked, y = Fare, Fill = factor(Pclass))) + geom_boxplot() + geom_hline(yintercept = 80, colour = "blue") + theme_grey()
full[full$Embarked == "", ]$Embarked <- "C"
full_embarked_s <- full[full$Embarked == "S" & full$Pclass == 3, ]
full_embarked_s <- full_embarked_s[!is.na(full_embarked_s$Fare), ]
ggplot(full_embarked_s, aes(x = Fare)) + geom_density(fill = "lightblue") + geom_vline(aes(xintercept = median(Fare)), color = "Red") + theme_base()
full$Fare[1044] <- median(full[full$Embarked == "S" & full$Pclass == 3, ]$Fare, na.rm = T)
set.seed(111)
mice_model <- mice(full[, c("Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Family", "title", "FType", "Embarked")], method = "rf")
mice_output <- complete(mice_model)
par(mfrow = c(1, 2))
hist(mice_output$Age, main = "Mice Output")
hist(full$Age, main = "OriginalData Output")
full$Age <- mice_output$Age
summary(full)
full$Adulch <- "NA"
full$Adulch <- ifelse(full$Age >= 18, "Major", "Minor")
full$Adulch <- as.factor(full$Adulch)
table(full$Adulch, full$Survived)
prop.table(table(full$Adulch, full$Survived), 1)
ggplot(full[1:891, ], aes(x = Adulch, fill = factor(Survived))) + geom_bar(stat = "count", position = "dodge")
full$SexAdulCh <- "NA"
full$SexAdulCh <- paste(full$Sex, full$Adulch)
full$SexAdulCh <- as.factor(full$SexAdulCh)
prop.table(table(full$SexAdulCh, full$Survived), 1)
ggplot(full[1:891, ], aes(x = SexAdulCh, fill = Survived)) + geom_bar(stat = "count", position = "dodge")
train1 <- full[1:891, ]
test1 <- full[892:1309, ]
set.seed(112)
str(train1)
rf_model <- randomForest(Survived ~ title + SexAdulCh + Pclass + Fare + Embarked + FType, train1)
plot(rf_model, ylim = c(0, 0.36))
legend("topright", colnames(rf_model$err.rate), col = 1:3, fill = 1:3)
importance <- importance(rf_model)
varImportance <- data.frame(Variables = row.names(importance), Importance = round(importance[, "MeanDecreaseGini"], 2))
ggplot(varImportance, aes(x = reorder(Variables, Importance), y = Importance, fill = Importance)) + geom_bar(stat = "identity") + labs(x = "Variables") + coord_flip() + theme_few()
Survival_Predicted <- data.frame(PassengerId = test1$PassengerId)
Survival_Predicted$Survived <- predict(rf_model, test1)
getwd()
write.csv(Survival_Predicted, file = "titanic_random_forest_r_submission.csv", row.names = FALSE)
